from fpdf import FPDF

# Candidate A - Full Stack Developer
pdf_a = FPDF()
pdf_a.add_page()
pdf_a.set_font("Arial", "B", 14)
pdf_a.cell(0, 10, "JOHN ANDERSON", ln=True)
pdf_a.set_font("Arial", "", 10)
pdf_a.cell(0, 5, "Senior Full Stack Developer | San Francisco, CA", ln=True)
pdf_a.cell(0, 5, "john.anderson@email.com", ln=True)
pdf_a.ln(3)

pdf_a.set_font("Arial", "B", 12)
pdf_a.cell(0, 8, "PROFESSIONAL SUMMARY", ln=True)
pdf_a.set_font("Arial", "", 10)
summary = """Experienced Full Stack Software Engineer with 6+ years of expertise in building scalable web applications. Proficient in Python, JavaScript, and modern web frameworks. Strong background in database design, API development, and cloud technologies."""
pdf_a.multi_cell(0, 4, summary)
pdf_a.ln(2)

pdf_a.set_font("Arial", "B", 12)
pdf_a.cell(0, 8, "CORE SKILLS", ln=True)
pdf_a.set_font("Arial", "", 10)
pdf_a.cell(0, 4, "Languages: Python, JavaScript, Java, SQL, HTML, CSS", ln=True)
pdf_a.cell(0, 4, "Frontend: React, HTML5, CSS3, responsive design", ln=True)
pdf_a.cell(0, 4, "Backend: Django, Flask, REST APIs, Node.js", ln=True)
pdf_a.cell(0, 4, "Databases: PostgreSQL, MySQL, MongoDB", ln=True)
pdf_a.cell(0, 4, "DevOps & Tools: Docker, AWS, Git, Linux, CI/CD", ln=True)
pdf_a.cell(0, 4, "Other: Microservices, Testing, Agile, Code review, Communication", ln=True)
pdf_a.ln(2)

pdf_a.set_font("Arial", "B", 12)
pdf_a.cell(0, 8, "WORK EXPERIENCE", ln=True)
pdf_a.set_font("Arial", "B", 10)
pdf_a.cell(0, 4, "Senior Full Stack Engineer | Tech Company (2020 - Present)", ln=True)
pdf_a.set_font("Arial", "", 10)
pdf_a.cell(0, 4, "- Developed Django and React applications handling millions of requests", ln=True)
pdf_a.cell(0, 4, "- Designed REST APIs and optimized PostgreSQL databases", ln=True)
pdf_a.cell(0, 4, "- Deployed Docker containers on AWS with CI/CD pipelines", ln=True)
pdf_a.cell(0, 4, "- Led code reviews and mentored junior developers", ln=True)

pdf_a.output("samples/candidate_A.pdf")
print("✓ Created candidate_A.pdf")

# Candidate B - Backend Engineer
pdf_b = FPDF()
pdf_b.add_page()
pdf_b.set_font("Arial", "B", 14)
pdf_b.cell(0, 10, "SARAH CHEN", ln=True)
pdf_b.set_font("Arial", "", 10)
pdf_b.cell(0, 5, "Backend Software Engineer | New York, NY", ln=True)
pdf_b.cell(0, 5, "sarah.chen@email.com", ln=True)
pdf_b.ln(3)

pdf_b.set_font("Arial", "B", 12)
pdf_b.cell(0, 8, "PROFESSIONAL SUMMARY", ln=True)
pdf_b.set_font("Arial", "", 10)
summary_b = """Talented Backend Software Engineer with 5+ years building robust server-side applications and microservices. Expert in Python and Java with deep knowledge of SQL databases and API design. Passionate about system architecture and performance optimization."""
pdf_b.multi_cell(0, 4, summary_b)
pdf_b.ln(2)

pdf_b.set_font("Arial", "B", 12)
pdf_b.cell(0, 8, "TECHNICAL SKILLS", ln=True)
pdf_b.set_font("Arial", "", 10)
pdf_b.cell(0, 4, "Languages: Python, Java, SQL", ln=True)
pdf_b.cell(0, 4, "Frameworks: Django, Flask, REST APIs, Spring Boot", ln=True)
pdf_b.cell(0, 4, "Databases: PostgreSQL, MySQL, Redis", ln=True)
pdf_b.cell(0, 4, "Cloud & DevOps: AWS, Docker, Kubernetes, Git", ln=True)
pdf_b.cell(0, 4, "Architecture: Microservices, System design, API Development", ln=True)
pdf_b.cell(0, 4, "Methodologies: Agile, Testing, Code review, Linux", ln=True)
pdf_b.ln(2)

pdf_b.set_font("Arial", "B", 12)
pdf_b.cell(0, 8, "WORK EXPERIENCE", ln=True)
pdf_b.set_font("Arial", "B", 10)
pdf_b.cell(0, 4, "Senior Backend Engineer | Enterprise Solutions (2021 - Present)", ln=True)
pdf_b.set_font("Arial", "", 10)
pdf_b.cell(0, 4, "- Architected microservices using Python and Docker", ln=True)
pdf_b.cell(0, 4, "- Designed efficient PostgreSQL schemas and optimized queries", ln=True)
pdf_b.cell(0, 4, "- Developed REST APIs handling 100k+ daily requests", ln=True)
pdf_b.cell(0, 4, "- Implemented CI/CD pipelines and automated testing", ln=True)
pdf_b.cell(0, 4, "- Mentored junior engineers on system design", ln=True)

pdf_b.output("samples/candidate_B.pdf")
print("✓ Created candidate_B.pdf")

# Candidate C - Frontend Developer
pdf_c = FPDF()
pdf_c.add_page()
pdf_c.set_font("Arial", "B", 14)
pdf_c.cell(0, 10, "ALEX MARTINEZ", ln=True)
pdf_c.set_font("Arial", "", 10)
pdf_c.cell(0, 5, "Full Stack Developer | Austin, TX", ln=True)
pdf_c.cell(0, 5, "alex.martinez@email.com", ln=True)
pdf_c.ln(3)

pdf_c.set_font("Arial", "B", 12)
pdf_c.cell(0, 8, "PROFESSIONAL SUMMARY", ln=True)
pdf_c.set_font("Arial", "", 10)
summary_c = """Creative Full Stack Developer with 4+ years of experience building modern web applications. Strong expertise in JavaScript, React, and Python backend development. Passionate about responsive design and clean code."""
pdf_c.multi_cell(0, 4, summary_c)
pdf_c.ln(2)

pdf_c.set_font("Arial", "B", 12)
pdf_c.cell(0, 8, "SKILLS", ln=True)
pdf_c.set_font("Arial", "", 10)
pdf_c.cell(0, 4, "Frontend: JavaScript, React, HTML5, CSS3", ln=True)
pdf_c.cell(0, 4, "Backend: Python, Django, Flask, REST APIs", ln=True)
pdf_c.cell(0, 4, "Databases: PostgreSQL, MongoDB", ln=True)
pdf_c.cell(0, 4, "Tools: Git, Docker, AWS, Linux", ln=True)
pdf_c.cell(0, 4, "Other: Testing, Code review, Agile, Communication", ln=True)
pdf_c.ln(2)

pdf_c.set_font("Arial", "B", 12)
pdf_c.cell(0, 8, "WORK EXPERIENCE", ln=True)
pdf_c.set_font("Arial", "B", 10)
pdf_c.cell(0, 4, "Full Stack Developer | Digital Innovations Ltd. (2021 - Present)", ln=True)
pdf_c.set_font("Arial", "", 10)
pdf_c.cell(0, 4, "- Developed responsive web applications using React and Django", ln=True)
pdf_c.cell(0, 4, "- Built and maintained Python Flask REST APIs", ln=True)
pdf_c.cell(0, 4, "- Worked with PostgreSQL database design and optimization", ln=True)
pdf_c.cell(0, 4, "- Deployed applications using Docker and AWS", ln=True)
pdf_c.cell(0, 4, "- Conducted code reviews and collaborated in agile sprints", ln=True)

pdf_c.output("samples/candidate_C.pdf")
print("✓ Created candidate_C.pdf")

print("\n✅ All readable resumes created successfully with FPDF!")
